name: CI Build (Compile Only, No Push)

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Bake all images (compile-only, no push)
        uses: docker/bake-action@v4
        with:
          files: |
            docker-bake.hcl
          push: false
          load: false
